<?php
/*===============================================================
*   Copyright (C) 2015 All rights reserved.
*
*   file        : Wechat.php
*   author      : jason.zhi
*   date        : 2016/12/26
*   description : 微信服务器号各种接口调用
*   modify      :
*
================================================================*/
namespace app\admin\controller;

use app\common\controller\Admin;

class Wechatservice extends Admin
{
    private $weObj;
    
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        
        vendor("Wechat");
        $this->config = config('WX.MP');
        
        $this->weObj = new \Wechat([
            'appid'     => $this->config['APPID'],
            'appsecret' => $this->config['AppSecret'],
            'token'     => 'weixin',
        ]);
    }
    
    /**
     * @brief  创建自定义菜单
     * @author jason.zhi@lihuobao.cn
     * @date   2016/10/31
     */
    public function createMenu()
    {
        $menu = [
            "button" => [
                [
                    "type" => "view",
                    "name" => "首页",
                    //"url"  => "http://" . C('WEIXIN_MP_CONFIG.request_host') . "/Wechat/Index/index",
                    "url"  => "https://m.imay.com/index/index",
                ],
                [
                    "type" => "view",
                    "name" => "充值",
                    //"url"  => "http://" . C('WEIXIN_MP_CONFIG.request_host') . "/Recharge/index",
                    "url"  => "https://m.imay.com/recharge/index",
                ],
                [
                    "type" => "view",
                    "name" => "提现",
                    //"url"  => "http://" . C('WEIXIN_MP_CONFIG.request_host') . "/Wechat/Withdraw/index",
                    "url"  => "https://m.imay.com/withdraw/index",
                ],
            ],
        ];
        $rs   = $this->weObj->createMenu($menu);
        var_dump($rs);
    }
}