version: '2'
services:
    gitlab:
      image: 'gitlab/gitlab-ce:latest'
      restart: always
      hostname: 'gitlab.game-magic.net'
      environment:
        TZ: 'Asia/Shanghai'
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'http://gitlab.game-magic.net'
          gitlab_rails['time_zone'] = 'Asia/Shanghai'
          gitlab_rails['smtp_enable'] = true
          gitlab_rails['smtp_address'] = "smtp.exmail.qq.com"
          gitlab_rails['smtp_port'] = 465
          gitlab_rails['smtp_user_name'] = "oa@game-magic.net"
          gitlab_rails['smtp_password'] = "Qq2015"
          gitlab_rails['smtp_authentication'] = "login"
          gitlab_rails['smtp_enable_starttls_auto'] = true
          gitlab_rails['smtp_tls'] = true
          gitlab_rails['gitlab_email_from'] = 'oa@game-magic.net'
      ports:
        - '10080:80'
        - '443:443'
        - '10022:22'
      volumes:
        - /srv/gitlab/config:/etc/gitlab
        - /srv/gitlab/data:/var/opt/gitlab
        - /srv/gitlab/logs:/var/log/gitlab
